language: python
cache:
  timeout: 1800
  pip: true


python:
  - 3.6


install:
  - pip install -r requirements.txt
  - pip install -r tests/requirements.txt
  - pip3 install gseapy
  - mkdir -p cudaGSEA/cudaGSEA/src
  - touch cudaGSEA/cudaGSEA/src/cudaGSEA


script:
 - bash run_tests.sh


after_success:
  - codecov
